version: '3'

services:
  postgres:
    image: bitnami/postgresql
    container_name: spacetime
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRESQL_USERNAME=dev
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=spacetime
    volumes:
      - ./data:/var/lib/postgresql/data